name: Deploy

on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Generate PEM
      run: echo "$PEM" >> techno.pem && chmod 400 techno.pem
      env:
        PEM: ${{secrets.PEM}}

    - name: Doing the magic now
      run: ssh -o StrictHostKeyChecking=no -i techno.pem ec2-user@ec2-3-111-170-203.ap-south-1.compute.amazonaws.com "cd TC_Backend && git pull && yarn install && pm2 restart 0 && sudo systemctl restart nginx"

    - name: LIVE!!!
      run: echo "Server Ready🚀🚀🚀"
