name: Deploy

on:
  push:
    branches:
      - main-ts

env:
  CI: false

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Installing dependencies
      run: npm install

    - name: Create new build for TS
      run: tsc
      
    - name: Generate PEM
      run: echo "$PEM" >> techno.pem && chmod 400 techno.pem
      env:
        PEM: ${{secrets.PEM}}

    - name: Removing older build
      run: ssh -o StrictHostKeyChecking=no -i techno.pem ec2-user@ec2-3-111-170-203.ap-south-1.compute.amazonaws.com "cd TC_Backend && git checkout main-ts && sudo rm -r build/* && sudo rm -r node_modules/*"

    - name: Copying new build
      run: scp -o StrictHostKeyChecking=no -i techno.pem -r build/* ec2-user@ec2-3-111-170-203.ap-south-1.compute.amazonaws.com:/home/ec2-user/TC_Backend/build
      
    - name: Doing the magic now
      run: ssh -o StrictHostKeyChecking=no -i techno.pem ec2-user@ec2-3-111-170-203.ap-south-1.compute.amazonaws.com "cd TC_Backend && git checkout main-ts && git pull origin main-ts && npm i && pm2 restart 0 && sudo systemctl restart nginx"

    - name: LIVE!!!
      run: echo "Server Ready🚀🚀🚀"
